name: Build

on:
  pull_request: {}
  push: { branches: [master, merge_requests] }

jobs:
  Release:
    name: Release
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build
      - name: Build
        run: |
          cmake -B build -G "Visual Studio 16 2019"
          cmake --build build --config Release -- -m

      # Tests
      - name: Tests
        run: |
          cd Build
          ctest

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Release
          path: build/Release/DofusBotFM.exe
          
  Debug:
    name: Debug
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build
      - name: Build
        run: |
          cmake -B build -G "Visual Studio 16 2019"
          cmake --build build --config Debug -- -m

      # Tests and Coverage
      - name: Tests and Coverage
        run: |
            choco install OpenCppCoverage -y
            $env:path += ";C:\Program Files\OpenCppCoverage"
            OpenCppCoverage.exe --sources DofusBotFM\src\ --export_type cobertura:coverage.xml .\build\test\Debug\DBFTests.exe

      # Upload Coverage
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          functionalities: fix

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Debug
          path: build/Debug/DofusBotFM.exe
